import AmazonOrderReferenceID from "./amazon-order-reference-id";
import { ExtensionAttributesAppliedTax } from "./extension-attributes-applied-tax";
import { GiftCard } from "./gift-cart";
import { GiftMessage } from "./gift-message";
import { ItemAppliedTax } from "./item.applied-tax";
import { CompanyOrderAttributes } from "./order-company-attributes";
import { OrderShippingAssignment } from "./order-shipping-assignment";
import { PaymentAdditionalInfo } from "./payment-additional-info";

export interface OrderExtensionAttributes {
  shipping_assignments?: OrderShippingAssignment[];
  payment_additional_info?: PaymentAdditionalInfo[];
  company_order_attributes?: CompanyOrderAttributes;
  applied_taxes?: ExtensionAttributesAppliedTax[];
  item_applied_taxes?: ItemAppliedTax[];
  converting_from_quote?: boolean;
  base_customer_balance_amount?: number;
  customer_balance_amount?: number;
  base_customer_balance_invoiced?: number;
  customer_balance_invoiced?: number;
  base_customer_balance_refunded?: number;
  customer_balance_refunded?: number;
  base_customer_balance_total_refunded?: number;
  customer_balance_total_refunded?: number;
  gift_cards?: GiftCard[];
  base_gift_cards_amount?: number;
  gift_cards_amount?: number;
  base_gift_cards_invoiced?: number;
  gift_cards_invoiced?: number;
  base_gift_cards_refunded?: number;
  gift_cards_refunded?: number;
  gift_message?: GiftMessage;
  gw_id?: string;
  gw_allow_gift_receipt?: string;
  gw_add_card?: string;
  gw_base_price?: string;
  gw_price?: string;
  gw_items_base_price?: string;
  gw_items_price?: string;
  gw_card_base_price?: string;
  gw_card_price?: string;
  gw_base_tax_amount?: string;
  gw_tax_amount?: string;
  gw_items_base_tax_amount?: string;
  gw_items_tax_amount?: string;
  gw_card_base_tax_amount?: string;
  gw_card_tax_amount?: string;
  gw_base_price_incl_tax?: string;
  gw_price_incl_tax?: string;
  gw_items_base_price_incl_tax?: string;
  gw_items_price_incl_tax?: string;
  gw_card_base_price_incl_tax?: string;
  gw_card_price_incl_tax?: string;
  gw_base_price_invoiced?: string;
  gw_price_invoiced?: string;
  gw_items_base_price_invoiced?: string;
  gw_items_price_invoiced?: string;
  gw_card_base_price_invoiced?: string;
  gw_card_price_invoiced?: string;
  gw_base_tax_amount_invoiced?: string;
  gw_tax_amount_invoiced?: string;
  gw_items_base_tax_invoiced?: string;
  gw_items_tax_invoiced?: string;
  gw_card_base_tax_invoiced?: string;
  gw_card_tax_invoiced?: string;
  gw_base_price_refunded?: string;
  gw_price_refunded?: string;
  gw_items_base_price_refunded?: string;
  gw_items_price_refunded?: string;
  gw_card_base_price_refunded?: string;
  gw_card_price_refunded?: string;
  gw_base_tax_amount_refunded?: string;
  gw_tax_amount_refunded?: string;
  gw_items_base_tax_refunded?: string;
  gw_items_tax_refunded?: string;
  gw_card_base_tax_refunded?: string;
  gw_card_tax_refunded?: string;
  pickup_location_code?: string;
  notification_sent?: number;
  send_notification?: number;
  reward_points_balance?: number;
  reward_currency_amount?: number;
  base_reward_currency_amount?: number;
  amazon_order_reference_id?: AmazonOrderReferenceID;
}
