/**
 *
 * @export
 * @enum {string}
 */
export enum V1DiscountType {
  UNSPECIFIED = "DISCOUNT_TYPE_UNSPECIFIED",
  MISC = "DISCOUNT_TYPE_MISC",
  REGULAR = "DISCOUNT_TYPE_REGULAR",
  SHIPPING = "DISCOUNT_TYPE_SHIPPING",
  HANDLING = "DISCOUNT_TYPE_HANDLING",
  WRAPPING = "DISCOUNT_TYPE_WRAPPING",
}
