/**
 *
 * @export
 * @enum {string}
 */
export enum V1SubResource {
  UNSPECIFIED = "SUB_RESOURCE_UNSPECIFIED",
  VARIANTS = "SUB_RESOURCE_VARIANTS",
  IMAGES = "SUB_RESOURCE_IMAGES",
  CUSTOMFIELDS = "SUB_RESOURCE_CUSTOM_FIELDS",
  BULKPRICINGRULES = "SUB_RESOURCE_BULK_PRICING_RULES",
  PRIMARYIMAGE = "SUB_RESOURCE_PRIMARY_IMAGE",
  MODIFIERS = "SUB_RESOURCE_MODIFIERS",
  OPTIONS = "SUB_RESOURCE_OPTIONS",
  VIDEOS = "SUB_RESOURCE_VIDEOS",
};
