/**
 *
 * @export
 * @enum {string}
 */
export enum V1WebhookScope {
  UNSPECIFIED = "WEBHOOK_SCOPE_UNSPECIFIED",
  ORDER = "WEBHOOK_SCOPE_ORDER",
  CUSTOMER = "WEBHOOK_SCOPE_CUSTOMER",
  CART = "WEBHOOK_SCOPE_CART",
  PRODUCT = "WEBHOOK_SCOPE_PRODUCT",
  COUPON = "WEBHOOK_SCOPE_COUPON",
  CATEGORY = "WEBHOOK_SCOPE_CATEGORY",
}
