/**
 *
 * @export
 * @enum {string}
 */
export enum V1CartToOrderConvert {
  UNSPECIFIED = "CART_TO_ORDER_CONVERT_UNSPECIFIED",
  ONLY = "CART_TO_ORDER_CONVERT_ONLY",
  UPDATEANDCONVERT = "CART_TO_ORDER_CONVERT_UPDATE_AND_CONVERT",
}
