/**
 * -------------------------------- Start: Common -------------------------------- //
 * @export
 * @enum {string}
 */
export enum V1EntityType {
  UNSPECIFIED = "ENTITY_TYPE_UNSPECIFIED",
  ORDER = "ENTITY_TYPE_ORDER",
  SHIPPINGOPTION = "ENTITY_TYPE_SHIPPING_OPTION",
  USER = "ENTITY_TYPE_USER",
  SHIPPINGZONES = "ENTITY_TYPE_SHIPPING_ZONES",
  CATALOGPRODUCT = "ENTITY_TYPE_CATALOG_PRODUCT",
  WEBHOOK = "ENTITY_TYPE_WEBHOOK",
  ORDERSYNC = "ENTITY_TYPE_ORDER_SYNC",
  CATALOGCATEGORY = "ENTITY_TYPE_CATALOG_CATEGORY",
}
