/**
 *
 * @export
 * @enum {string}
 */
export enum V1ItemFulfillmentMode {
  UNSPECIFIED = "ITEM_FULFILLMENT_MODEL_UNSPECIFIED",
  PHYSICAL = "ITEM_FULFILLMENT_MODEL_PHYSICAL",
  DIGITAL = "ITEM_FULFILLMENT_MODEL_DIGITAL",
  SERVICE = "ITEM_FULFILLMENT_MODEL_SERVICE",
}
