/**
 *
 * @export
 * @enum {string}
 */
export enum V1ModifierType {
  UNSPECIFIED = "MODIFIER_TYPE_UNSPECIFIED",
  DATE = "MODIFIER_TYPE_DATE",
  CHECKBOX = "MODIFIER_TYPE_CHECKBOX",
  FILE = "MODIFIER_TYPE_FILE",
  TEXT = "MODIFIER_TYPE_TEXT",
  MULTILINETEXT = "MODIFIER_TYPE_MULTI_LINE_TEXT",
  NUMBERSONLYTEXT = "MODIFIER_TYPE_NUMBERS_ONLY_TEXT",
  RADIOBUTTONS = "MODIFIER_TYPE_RADIO_BUTTONS",
  RECTANGLES = "MODIFIER_TYPE_RECTANGLES",
  DROPDOWN = "MODIFIER_TYPE_DROPDOWN",
  PRODUCTLIST = "MODIFIER_TYPE_PRODUCT_LIST",
  PRODUCTLISTWITHIMAGES = "MODIFIER_TYPE_PRODUCT_LIST_WITH_IMAGES",
  SWATCH = "MODIFIER_TYPE_SWATCH",
};
