/**
 *
 * @export
 * @enum {string}
 */
export enum V1OrderType {
  UNSPECIFIED = "ORDER_TYPE_UNSPECIFIED",
  CART = "ORDER_TYPE_CART",
  ORDER = "ORDER_TYPE_ORDER",
  RETURN = "ORDER_TYPE_RETURN",
  EXCHANGE = "ORDER_TYPE_EXCHANGE",
  CREDIT = "ORDER_TYPE_CREDIT",
  REFUND = "ORDER_TYPE_REFUND",
}
