/**
 *
 * @export
 * @enum {string}
 */
export enum V1UpdateOrderSegmentType {
  UNSPECIFIED = "UPDATE_ORDER_SEGMENT_TYPE_UNSPECIFIED",
  COUPON = "UPDATE_ORDER_SEGMENT_TYPE_COUPON",
  SHIPPINGADDRESS = "UPDATE_ORDER_SEGMENT_TYPE_SHIPPING_ADDRESS",
  BILLINGADDRESS = "UPDATE_ORDER_SEGMENT_TYPE_BILLING_ADDRESS",
  LINEITEM = "UPDATE_ORDER_SEGMENT_TYPE_LINE_ITEM",
  SHIPPINGOPTION = "UPDATE_ORDER_SEGMENT_TYPE_SHIPPING_OPTION",
  CONVERTCARTTOORDER = "UPDATE_ORDER_SEGMENT_TYPE_CONVERT_CART_TO_ORDER",
  ORDERSTATUS = "UPDATE_ORDER_SEGMENT_TYPE_ORDER_STATUS",
};
